### ISSUE TITLE
Problem with importing using build tool like Snowpack

### ISSUE THREAD

**Issue by drohen** [RepComm/gameinput-ts#6]
Due to [this specification in snowpack](https://www.snowpack.dev/reference/common-error-details#uncaught-syntaxerror-the-requested-module-xxxxxxjs-does-not-provide-an-export-named-yyyyyy), importing the library fails due to `mod.js` exporting typescript types.

I can try and make a PR, but basically what makes it work is ensuring mod.js only exports references to actual JS code, such as `GameInput` and leave the rest up to the .d.ts files.

**Comment by RepComm** [comment]
I'd be perfectly fine with that.
The more possible use cases the better!

edit- I have no experience with this issue, but I imagine I have a few packages that might cause the same issue.
I am interested in learning how to resolve your issue in general.

**Comment by RepComm** [comment]
So I'm tracking that I'm not having an issue with [@repcomm/exponent-ts](https://github.com/RepComm/exponent-ts) and went to check what the difference was, and it seems I never exported any `interface` or `type` from that package, which seems to be what is keeping it working in snowpack on my end, which I can't say for gameinput.

I have removed the type/interface exports from mod.ts and will test it in a few minutes in snowpack. If all goes well I will push and update npm as well.

**Comment by RepComm** [comment]
Okay, I have tested in `"snowpack": "^3.8.3"` and it's running for me now.
If you are using this version of snowpack, can you check if your issue is resolved for me?

Latest NPM module version with the fix is `"@repcomm/gameinput-ts": "^1.10.4"`
There are also some API changes, so be sure to read the ReadMe.md

A key different would be createButton and createAxis have been made private, you should use getOrCreateButton or getOrCreateAxis instead now.

@drohen

**Comment by drohen** [comment]
Works great! Thanks for doing this :+1:
